version: '3.4'


services:
  webserver:
    container_name: webserver
    image: ${DOCKER_REGISTRY-}webserver
    build:
      context: .
      dockerfile: WebServer/Dockerfile
    networks: 
     - my-net
    volumes:
    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  sql-server-db:
   container_name: user-db
   image: postgres
   networks: 
     - my-net
   ports:
   - "5432:5432"
   environment:
    POSTGRES_DB: "usersdb"
    POSTGRES_USER: "SA"
    POSTGRES_PASSWORD: "avRK-LnF1n" 
networks:
  my-net:
    driver: bridge